# ============================================================
# GitHub Actions Workflow: Build and Publish Recipes Site
#
# Description:
# This workflow builds the static website of recipes from the files located in the
# `cooklang/` folder.
#
# Trigger Conditions:
# - On push to the `prod` branch
# - Only if files inside the `cooklang/` directory have changed
#
# Manual Trigger:
# - Can also be triggered manually via the GitHub Actions interface.
# ============================================================

name: Publish recipes
on:
  push:
    branches: [ 'prod' ]
    paths: ['cooklang/**']
  workflow_dispatch:
permissions:
  contents: write
jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install CookCLI
        run: |
          curl -L https://github.com/cooklang/cookcli/releases/latest/download/cook-x86_64-unknown-linux-gnu.tar.gz \
            | tar xz
          sudo mv cook /usr/local/bin/
      - name: Build Site
        run: cook build web --base-path ./ ./_site