# ============================================================
# GitHub Actions Workflow: Build and Publish Cooklang Website
#
# Description:
# This workflow builds the static website of recipes from the files located in the
# `cooklang/` folder.
#
# Trigger Conditions:
# - On push to the `prod` branch
# - Only if files inside the `cooklang/` directory have changed
#
# Manual Trigger:
# - Can also be triggered manually via the GitHub Actions interface.
# ============================================================

name: Build and Publish Cooklang Website
run-name: Build and Publish Cooklang Website
on:
  push:
    branches: [ 'prod' ]
    paths: ['cooklang/**']
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install CookCLI
        run: |
          curl -L https://github.com/cooklang/cookcli/releases/download/v0.32.0/cook-x86_64-unknown-linux-gnu.tar.gz \
            | tar xz
          mv cook /usr/local/bin/

      - name: Build site
        run: cook build web --base-path ./cooklang/ ./_site

      - name: Commit and Push generated site
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Force push because _site/ is in the .gitignore
          git add -f _site/.
          if git diff-index --quiet HEAD -- _site; then
            echo "The site is up-to-date. No changes to commit."
          else
            git commit -m "bot: build site"
            git push origin prod
          fi